fprintf("caricamento dati...\n");
load("data/data.mat");
fprintf("totale features estratte: %d", size(training_data, 2) - 1);
clear training_data testing_data training_data_unknown testing_data_unknown;

fprintf("caricamento classifier... \n")
load("data/classifier.mat");
fprintf("accuracy del classifier sul test set: %.2f%%\n", test_accuracy * 100);
fprintf("numero di features selezionate: %d\n", size(classifier.PredictorNames, 2))

fprintf("caricamento detector... \n")
load("data/detector.mat");
fprintf("accuracy del detector sul test set: %.2f%%\n", test_accuracy * 100);
fprintf("numero di features selezionate: %d\n", size(detector.PredictorNames, 2))

fprintf("testing su altre immagini...\n");
fprintf("avviamento parallel pool... \n")
fprintf("testing su training e test set (basato su istanze)\n");
test_classify_image(classifier, detector, scaling_data, ...
                    directory="dataset/03_classes", ...
                    standardize=true, DoParallel=false, ...
                    visualize_predictions=false, ...
                    visualize_confmat=false);

fprintf("testing su misc set\n");
test_classify_image(classifier, detector, scaling_data, ...
                    directory="dataset/05_miscs", ...
                    standardize=true, DoParallel=false, ...
                    visualize_predictions=false, ...
                    visualize_confmat=false);

fprintf("testing su unknown set\n");
test_classify_image(classifier, detector, scaling_data, ...
                    directory="dataset/06_unknown_miscs", ...
                    standardize=true, doparallel=false, ...
                    visualize_predictions=false, ...
                    visualize_confmat=false);
